In [4]:
import cv2
import numpy as np

# Carregue a imagem usando o OpenCV
#imagem = cv2.imread('prentobranco.jpg')
imagem = cv2.imread('colorido.png')

print(imagem)

# Verifique se a imagem foi carregada com sucesso
if imagem is not None:
    # Converta a imagem para escala de cinza
    imagem_gray = cv2.cvtColor(imagem, cv2.COLOR_BGR2GRAY)
    
    # Calcule a escala de cinza média dos pixels
    media_escala_de_cinza = np.mean(imagem_gray)
    #print(media_escala_de_cinza)    
    
    # Defina um limite para determinar se a imagem é em preto e branco
    limite_escala_de_cinza = 70  # Ajuste esse valor conforme necessário
    
    if media_escala_de_cinza < limite_escala_de_cinza:
        print("A imagem é em preto e branco.")
    else:
        print("A imagem é colorida.")
    
    # Exiba a imagem (opcional)
    cv2.imshow('Imagem', imagem)
    cv2.waitKey(0)
    cv2.destroyAllWindows()
else:
    print("Não foi possível carregar a imagem.")


[[[ 58 124 144]
  [ 56 122 142]
  [ 54 119 139]
  ...
  [ 26 122 154]
  [ 27 122 155]
  [ 32 126 159]]

 [[ 59 125 146]
  [ 57 123 144]
  [ 54 119 140]
  ...
  [ 30 125 157]
  [ 32 126 159]
  [ 37 131 163]]

 [[ 62 128 149]
  [ 60 126 147]
  [ 56 122 143]
  ...
  [ 34 128 161]
  [ 37 131 164]
  [ 43 136 169]]

 ...

 [[ 71 243 248]
  [ 72 242 248]
  [ 73 242 248]
  ...
  [ 30  54  66]
  [ 30  53  66]
  [ 31  52  66]]

 [[ 70 243 248]
  [ 70 243 247]
  [ 71 242 247]
  ...
  [ 29  54  66]
  [ 28  51  64]
  [ 27  50  63]]

 [[ 67 243 246]
  [ 68 242 245]
  [ 68 241 245]
  ...
  [ 29  53  64]
  [ 28  51  62]
  [ 28  49  61]]]
A imagem é colorida.


In [7]:
import numpy as np
import cv2

img = np.zeros((3, 3), dtype=np.uint8)

print(img)


img = cv2.cvtColor(img, cv2.COLOR_GRAY2BGR)

print(img)

window_name = 'Minha Janela'


cv2.imshow(window_name, img)
cv2.imwrite('file.jpg', img)

cv2.waitKey(0)
cv2.destroyAllWindows()

[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]


In [2]:
import cv2
import numpy
import os
# Make an array of 120,000 random bytes.
randomByteArray = bytearray(os.urandom(120000))
flatNumpyArray = numpy.array(randomByteArray)
# Convert the array to make a 400x300 grayscale image.
grayImage = flatNumpyArray.reshape(300, 400)
cv2.imwrite('RandomGray.png', grayImage)
# Convert the array to make a 400x100 color image.
bgrImage = flatNumpyArray.reshape(100, 400, 3)
cv2.imwrite('RandomColor.png', bgrImage)
img = cv2.imread('RandomColor.png')
cv2.imshow('RandomColor.png',img)


In [1]:
cv2.destroyAllWindows()

NameError: name 'cv2' is not defined