In [2]:
'''
Comandos básicos
'''
#instalação do numpy
%pip install numpy

#imporação
import numpy as np

#exibir a função
print(np.__version__)

Note: you may need to restart the kernel to use updated packages.
1.24.3


In [3]:
'''
Crie um array numpy com três números
'''

var = np.array([1,2,3])
print(var)

[1 2 3]


In [5]:
'''
Mostre que o array é uma instância do numpy
'''
if isinstance(var, np.ndarray):
    print ("sou uma instancia numpy")
else:
    print ("não sou uma instancia numpy")

sou uma instancia numpy


In [20]:
'''
Crie um array do tipo numpy contendo 15 elementos de valor zero:
'''

var = np.zeros(15)

print(var)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [19]:
'''
Crie uma array Numpy de formato 4x4 preenchida com elementos de valor inicial zero. Tais elementos devem ser de tipo inteiro.
'''
array = np.zeros(shape=(4,4), dtype="int")
print(array)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [23]:
'''
Crie um array numpy composta de 10 elementos, todos de valor 5
'''

array = np.ones(10) * 5

print(array)

[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


In [26]:
#Crie um array numpy composta de números inteiros, dentro do intervalo de 10 a 40:

array = np.arange(10,41)

print(array)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40]


In [32]:
#Crie um array numpy composta de elementos de valores pares, dentro do intervalo de 10 a 50

array = np.arange(10,51,2)

print(array)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


In [38]:
#crie um array numpy de formato 3x3 composta de valores inteiros entre 0 e 8
array = np.arange(9)
array = array.reshape(3, 3)
print(array)
#ou 
array = np.arange(9).reshape(3,3)
print(array)


[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [41]:
#crie um array numpy de formato 10x10, preenchida com o valor 128, sendo cada elemento do tipo float:
#array = (np.zeros(100) + 128).reshape(10,10)
#print(array)

array = np.full(shape=(10,10), fill_value=128, dtype="float")
print(array)

[[128. 128. 128. 128. 128. 128. 128. 128. 128. 128.]
 [128. 128. 128. 128. 128. 128. 128. 128. 128. 128.]
 [128. 128. 128. 128. 128. 128. 128. 128. 128. 128.]
 [128. 128. 128. 128. 128. 128. 128. 128. 128. 128.]
 [128. 128. 128. 128. 128. 128. 128. 128. 128. 128.]
 [128. 128. 128. 128. 128. 128. 128. 128. 128. 128.]
 [128. 128. 128. 128. 128. 128. 128. 128. 128. 128.]
 [128. 128. 128. 128. 128. 128. 128. 128. 128. 128.]
 [128. 128. 128. 128. 128. 128. 128. 128. 128. 128.]
 [128. 128. 128. 128. 128. 128. 128. 128. 128. 128.]]


In [179]:
#crie um array numpy composta por apenas um elemento numérico aleatório de valor entre 0 e 1

array = np.random.rand(1)

print(array)

[0.09762428]


In [192]:
#crie um array numpy composta por apenas 25 elementos numéricos aleatório de valores naturais

array = np.random.randn(25)

print(array)

[-0.24212323  0.80816485 -0.35884275 -0.32548306 -2.64240835  0.97560638
 -1.58286273 -0.69345081  0.52250582 -0.0055642   1.40050635 -0.4600096
  1.84330206  0.94559357  0.14814626 -0.52433911 -0.69234825  0.65527493
  0.4950392   1.76777271  0.93346006 -1.11551626  1.12615702 -0.54099362
 -1.84530258]


In [200]:
# agora com 26 inteiros, e dimenção de 2x5

array = np.random.randint(1,100, size=26)
print(array)
print(array.reshape(2,13))

[21 49  2  6 58 61 79 34 58 65 97 79 35 36 35 79 88 61 90 42 20 27 75 91
 98 82]
[[21 49  2  6 58 61 79 34 58 65 97 79 35]
 [36 35 79 88 61 90 42 20 27 75 91 98 82]]


In [228]:
#dada uma matriz inicial de formato 5 x 5, composta de elementos numéricos
#sequenciais entre 20 e 45, gere um novo array numpy contendo elementos 
#a partir da terceira linha e segunda coluna da matriz de origem

array = np.arange(20,45).reshape(5,5)
print(array)

print("")

array2 = array[2:, 1:]
print(array2)

[[20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]
 [40 41 42 43 44]]

[[31 32 33 34]
 [36 37 38 39]
 [41 42 43 44]]
